[environments]
  production.postgres.DATABASE_URL = "${DATABASE_URL}"
  production.env.USE_POSTGRES = "true"
  production.BUILD_COMMAND = "pip install -r requirements.txt"
  production.START_COMMAND = "gunicorn main:app"
